const express = require('express')
const router = express.Router()
const {checkUser}=require('../Middleware/authuser')
const {register,login,verifyuser,isUserAuth}=require('../Controller/authController')
const {UserResort,UserResortMain,getoneresort,getsimilarstay,UserAdventure,UserDestinations,getoneAdv,getonedest,getbookeddata,resort_book, verifyPayment,CancelBooking,updatePassword,getStaff}=require('../Controller/UserController')
const {createChat,UserChats,findChat}=require('../Controller/ChatController')
const {addMessage,getMessage}=require('../Controller/MessageController')
router.get('/')
router.post('/',verifyuser)
router.post('/register',register)
router.post('/login',login)
router.post('/verifyEmail/:id',verifyuser)
router.get('/resortList',UserResort)
router.get('/resortlistmain',UserResortMain)
router.get('/isUserAuth',checkUser,isUserAuth)
router.get('/oneResort/:id',getoneresort)
router.get('/getsimiliarstay/:data',getsimilarstay)
router.get('/adventureList',UserAdventure)
router.get('/destinations',UserDestinations)
router.get('/oneAdv/:id',getoneAdv)
router.get('/oneDest/:id',getonedest)
// router.post('/booking',checkUser,resort_booking)
router.post('/bookedResort',checkUser,resort_book)
router.post('/verifyPayment',checkUser,verifyPayment)
router.get('/getBookeddata',checkUser,getbookeddata)
router.post('/cancelBooking/:id',checkUser,CancelBooking)
router.post('/updatePassword',checkUser,updatePassword)
// chat backend begins
router.post('/createChat',checkUser,createChat)
router.get('/getUserChat/:userId',checkUser,UserChats)
router.get('/getchat/find/:firstId/:secondId',checkUser,findChat)
// message beackend
router.post('/addMsg',checkUser,addMessage)
router.get('/getMsg/:chatId',checkUser,getMessage)
router.get('/getStaffData/:id',checkUser,getStaff)


module.exports=router;
